version: '2'
services:
  sidecar-restore-volumes:
      image: nutellinoit/sidecar-restore-mysql:latest
      restart: "no"
      environment:
        - MYSQL_HOST=${MYSQL_HOST}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - TAR_TO_RESTORE=${TAR_TO_RESTORE}
        - S3_BUCKET=${S3_BUCKET}
        - S3_KEY=${S3_KEY}
        - S3_SECRET=${S3_SECRET}
        - S3_HOST=${S3_HOST}
        - S3_PROTOCOL=${S3_PROTOCOL}
##################
##### example db
  db:
      image: mysql:5.7.22
      restart: always
      ports:
        - "3307:3306" #only test
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}